site_name: Quicken Help Guide

nav:
  - Home: index.md
  - Setup: setup.md
  - FAQs: faq.md
  - Troubleshooting: troubleshooting.md

theme:
  name: mkdocs

extra:
  meta:
    - name: "msvalidate.01"
      content: "7CAA4CDA4793B2BCF1F40EDE348E7D04"
